#!/usr/bin/env python3
from subprocess import check_output as co
from sys import argv
import json
#help(json)
data = json.loads(co('ceph -f json pg ls active',shell=True).decode())['pg_stats']
from pprint import pprint
l=[]
for i in data:
    l.append((i['pgid'],i['last_deep_scrub_stamp']))
l.sort(key=lambda x: x[-1])
l=[i for i in l][:int(argv[1])]
from subprocess import check_call as cc
for i in l:
    cc(['ceph','pg','deep-scrub',i[0]])


