#!/bin/sh
ran -r -- rc-service -D netmount stop
sleep 60
ran -r -N $(hostname) tc -- 'rc-service -D netmount stop && openrc-shutdown -H now'
sleep 60
ran -r -N $(hostname) tc -- 'openrc-shutdown -H now'
sleep 60
power_disknodes_off
power_dusteater_off
openrc single_node
power_disknodes_off
power_dusteater_off

openrc-shutdown -p now & 
sleep 180
power_tc_off
power_all_nodes_off
