#!/bin/fish

# unit: Mib
set minfree 50000

# unit: sleep_time 
set interval 300


# parse args
set index_last_arg 0
for i in (seq (count $argv))
    if test (string sub -s1 -l1 -- $argv[$i]) = -
        set index_last_arg $i
    end
end
set argvlen (count $argv)
set consumed 0
if test $index_last_arg -gt 0
    for i in (seq $index_last_arg)
        if test $argv[$i] = "-i"
            if test $argvlen -gt $i
                set interval = $argv[(math "$i + 1")]
                set consumed (math $consumed + 2)
            end
        end
        if test $argv[$i] = "-m"
            if test $argvlen -gt $i
                set minfree = $argv[(math "$i + 1")]
                set minfree (math "$minfree"'*1024^3')
                set consumed (math $consumed + 2)
            end
        end
    end
end

set pathes_index (math $index_last_arg + 2)
set pathes $argv[(math $index_last_arg + 2)..-1]
echo pathes = \"$pathes\"
set  btrfs_args $argv[(math $consumed + 1)..-1]
echo btrfs_args = $btrfs_args


echo "bn sudo btrfs fi def -czstd -f -r  $btrfs_args &"
bn sudo btrfs fi def -czstd -f -r  $btrfs_args &
set pid (jobs -lp)



echo "min-free-disk  = $minfree Mib" 
echo "check-interval = $interval s"

set counter 0
set done no
while test $done = no
    set counter (math $counter + 1)
    jobs -q
    or break
    if test (math "$counter % $interval") -eq 0
        set free_spaces (df --output=avail /|tail -n+2)
        for i in $free_spaces
            test $i -lt $minfree
            #and sudo kill -sINT $pid
            and sudo killall -sINT btrfs
            and set done yes
            and echo sigint sent
            and break
        end
    end
    sleep 1
end
