#!/usr/bin/env python3
import pexpect
cmdl_lowp=pexpect.split_command_line('nice -n19 ionice -c3 sudo emerge')
from sys import argv
cmdl=cmdl_lowp+argv[1:]
print(cmdl[0],cmdl[1:])
pexpect.spawn(cmdl[0],cmdl[1:])
p=pexpect.spawn(cmdl[0],cmdl[1:])
p.interact()
