#!/usr/bin/python3
from sys import argv
import pexpect
from shlex import split as splitcmd
cmd1=splitcmd('bn sudo emerge')
cmd2=splitcmd('--ask -v')
cmd3=argv[1:]


cmd=cmd1+cmd2+cmd3
print(cmd)
p=pexpect.spawn(cmd[0],cmd[1:])
p.interact()
from sys import exit
p.close()
exit(p.exitstatus)
