#!/bin/sh
# Copyright 2008-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

chost_and_hostname="${0#*_}"
HOSTNAME="${chost_and_hostname##*_}"
CHOST="${chost_and_hostname%%_${HOSTNAME}}"
#mount "/node/${HOSTNAME}" || exit 1

export CHOST

BROOT=""
if [ "${BROOT}" = "@"GENTOO_PORTAGE_EPREFIX"@" ] ; then
	BROOT=""
fi

: ${EPREFIX=}
: ${SYSROOT=${BROOT}/node/${HOSTNAME}}
: ${ROOT=${SYSROOT}}
: ${PORTAGE_CONFIGROOT=${SYSROOT}${EPREFIX}}
export EPREFIX SYSROOT PORTAGE_CONFIGROOT ROOT
echo "BROOT              = \"${BROOT}\""
echo "EPREFIX            = \"${EPREFIX}\""
echo "ROOT               = \"${ROOT}\""
echo "SYSROOT            = \"${SYSROOT}\""
echo "PORTAGE_CONFIGROOT = \"${PORTAGE_CONFIGROOT}\""
echo "CHOST              = \"${CHOST}\""

if [ -z "${CHOST}" ] || [ ! -d "${SYSROOT}" ] ; then
	echo "cross-emerge: CHOST is not set properly"
	exit 1
fi

## Portage defaults CBUILD to CHOST, so we have to remove CHOST
## from the env to get a "good" value for CBUILD
#query_vars="CBUILD CFLAGS CXXFLAGS CPPFLAGS LDFLAGS"
#clean_vars="${query_vars} CHOST SYSROOT PORTAGE_CONFIGROOT"
#eval $(env $(printf -- '-u %s ' ${clean_vars}) \
#	portageq envvar -v ${query_vars} | sed s:^:_E_:)
#: ${CBUILD=${_E_CBUILD}}
#: ${BUILD_CFLAGS=${_E_CFLAGS}}
#: ${BUILD_CXXFLAGS=${_E_CXXFLAGS}}
#: ${BUILD_CPPFLAGS=${_E_CPPFLAGS}}
#: ${BUILD_LDFLAGS=${_E_LDFLAGS}}
#export CBUILD BUILD_CFLAGS BUILD_CXXFLAGS BUILD_CPPFLAGS BUILD_LDFLAGS
echo "CBUILD         = \"${CBUILD}\""
echo "BUILD_CFLAGS   = \"${BUILD_CFLAGS}\""
echo "BUILD_CXXFLAGS = \"${BUILD_CXXFLAGS}\""
echo "BUILD_CPPFLAGS = \"${BUILD_CPPFLAGS}\""
echo "BUILD_LDFLAGS  = \"${BUILD_LDFLAGS}\""
echo "CHOST          = \"${CHOST}\""
#echo "CFLAGS   = \"$(portageq CFLAGS   )\""
#echo "CXXFLAGS = \"$(portageq CXXFLAGS )\""
#echo "CPPFLAGS = \"$(portageq CPPFLAGS )\""
#echo "LDFLAGS  = \"$(portageq LDFLAGS  )\""

: ${CROSS_CMD:=emerge --root-deps=rdeps}
exec ${CROSS_CMD} "$@"
