#!/usr/bin/env python3
from sys import stdout
outp=[1.3,2.4,3.1,4.1] # list of floats
o=[f"{i:4.3f}" for i in outp]
print(f"{o[0]:8} {o[1]:7}"+" "*24,end="")
print(f"{o[2]:8} {o[3]:7}"+" "*24,end="")
