#!/usr/bin/env python3
from sys import stdout
o=["0123456","0123456","xyz","abc"]
print(" "*120,end="")
print("           x     0123__aaaaaxxxxx______",end="\r")
print("           x        0123____________-xy",end="\r")
