#!/bin/fish

if test (count $argv) -gt 0
	test $argv[1] = branch
    	and set argv $argv[2..-1]
else
	# if no branchname supplied use "git head branch"
	set argv (ghb)
end

git branch -m $argv[1] $argv[1]_(date '+%F')
or git branch -m $argv[1] $argv[1]_(date '+%F-%H-%M')
