#!/usr/bin/env python3

from argparse import ArgumentParser
from pylib.git_utils import find_git_dirs
from pylib.git_utils import unpack_packs

def parse_args():
    ap=ArgumentParser("""To remove the redundant packs after the program has ran,
        read the "git gc" manpage.
        As I tried, a "git gc" run cleaned them up.
        """)
    ap.add_argument(dest="path",default=".",nargs="+")
    ap.add_argument("-v","--verbose",action="store_true")
    return ap.parse_args()

def find_all_git_dirs(pathes,verbose=False):
    gitdirs = find_git_dirs(pathes[0],verbose=verbose)
    for p in pathes[1:]:
        gd=find_git_dirs(p,verbose=verbose,msg_out=msg_out)
        if not gd in gitdirs:
            gitdirs.append(gd)
    return gitdirs

if __name__ == "__main__":
    args=parse_args()
    pathes=args.path
    gitdirs=find_all_git_dirs(pathes,verbose=args.verbose)
    unpack_packs(gitdirs,verbose=args.verbose)

# vim: foldlevel=0 foldnestmax=3 foldmethod=indent :
