#!/usr/bin/env python3

from subprocess import check_output
from math import inf
from argparse import ArgumentParser
from re import sub



def prep0(out):
    out=[i for i in out.split(' ')]
    out=[i.strip(',)+-(') for i in out]
    out=[out[0],out[3],out[5]]
    return [int(i) for i in out]

if __name__=="__main__":
    ap=ArgumentParser   (   'Finds min diff in a refs history to another constant ref.'
                            'Supply one of the refs with "{}" brackets.'
                            'They will get substituted by a number.'
                            'like this \'foo/bar~{}\''
                            'will become foo/bar~0, foo/bar~1, ... till count'
                        )
    ap.add_argument(dest='const_ref')
    ap.add_argument(dest='ref')
    ap.add_argument('count',type=int)
    args=ap.parse_args()
    min=inf
    min_i=None
    for i in range(args.count):
        try:
            out=check_output(['gd','--shortstat', args.const_ref, sub('[{].*[}]',f'{i}',args.ref)]).decode().strip()
            out=prep0(out)
            s=sum(out[1:])
            if s < min:
                min=s
                min_i=i
        except Exception as e:
            print(e)
            break

    print(f'min_i = {min_i}\nminimum = {min}')
    
    
