#!/usr/bin/python3
from sys import argv
from os.path import expanduser
import github

with open(expanduser("~/.github_username")) as f:
    github_username=f.read().strip()

passwd=input('enter pass:')
gh=github.MainClass.Github(login_or_token=github_username, password=passwd)
user=gh.get_user()
user.create_repo(argv[1], private=False,  auto_init=False)
