#!/usr/bin/python3
from sys import argv
import github
passwd=input('enter pass:')
gh=github.MainClass.Github(login_or_token='alexander-n8hgeg5e', password=passwd)
user=gh.get_user()
user.create_repo(argv[1], private=False,  auto_init=False)
