#!/bin/fish 
set gitpack $argv[1]
echo checking gitpack: $gitpack
gsp -f ~/.gitpacks/$gitpack  -C '\
gd --quiet --exit-code refs/remotes/github/master -- 
and begin
    echo -n 1b5b306d|xxd -p -r
    echo -n (pwd)" = "
    echo -n 1b5b306d1b5b33326d |xxd -p -r
    echo "ok"
    echo -n 1b5b306d|xxd -p -r
end
or begin
    echo -n 1b5b306d|xxd -p -r
    echo -n (pwd)
    echo -n 1b5b306d1b5b33316d | xxd -p -r
    echo " failed"
    echo -n 1b5b306d|xxd -p -r
end' \
|grep -v 'bad revision'|rev|sort|rev
