#!/bin/fish
set args $argv
test $args[1] = push
    and set args $args[2..-1]

    git remote update $args[1] 
and git push $args[1] $args[2]
or  git push $args[1] $args[2]:$args[2]_(hostname)
or  git push $args[1] $args[2]:$args[2]_(hostname)_(date '+%F')
or  git push $args[1] $args[2]:$args[2]_(hostname)_(date '+%F-%H-%M')
