#!/usr/bin/env python3
from argparse import ArgumentParser
from os.path import abspath,exists
from sys import exit
from subprocess import check_call
a=ArgumentParser()
a.add_argument("-p","--path",default=None ,help="path to operate on")
a.add_argument("-gid","--group-id", type=int ,default=None ,help="path to operate on")
a.add_argument("-g","--group",type=str ,default=None ,help="path to operate on")
a.parse_args()
args=a.parse_args()

path=abspath(args.path)

if not exists(path):
    raise Exception("ERROR: need path")
if not args.group_id and not args.group:
    raise Exception("ERROR: need group or group-id")
if args.group_id and not args.group:
    int(args.group_id)

group=(args.group if args.group else (str(args.group_id)))

cmds = [[ 'sudo'  , 'find', path, '-type', 'd', '-exec', 'chmod' , 'g+s' ,'{}' , ';' ]]
cmds+= [[ 'chown' , '-R', ':'+group , path ]]
cmds+= [[ 'chmod' , '-R', 'g+rX', path ]]

for cmd in cmds:
    print(cmd)
    check_call(cmd)

