#!/usr/bin/python3
from subprocess import check_call,call
from time import sleep

def on():
    call(["rf","121"])
    sleep 0.5
    call(["rf","121"])

def off():
    call(["rf","120"])
    sleep 0.5
    call(["rf","120"])

for i in 

