#!/bin/fish
set node $argv[1]

test (count $argv) -gt 1
and test ( string length $argv[2]) -gt 0
and set timeout $argv[2]
or  set  timeout 3

ssh -o ConnectTimeout=$timeout $node "ps -u ""$list_my_procs_on_node_username"" --no-header -o pmem,pcpu,comm"|sed -E 's/$/  '$node'/'

#for pid in $a
#     list_proc_on_node_by_pid $node $pid $timeout &
#end
