#!/bin/fish

# restart if status is crashed
rc-status -c|grep -o offlineimap;and sudo rc-service offlineimap restart

notmuch new
if test (cat /proc/mounts|grep notmuchfs|grep -c $HOME/.my_notmuchfs) -lt 1
  mount-notmuchfs
end
