#!/bin/fish

function ff --description 'gimme ebuild'
    find . -name '*.ebuild' -type f
	end


function fff --description 'gimme manifs'
    find . -name '*.ebuild' -type f
	end

for i in (ff)
	echo $i
	ebuild $i manifest

    chown :portage $i
	chmod  g+r $i
end


for i in (fff)
    chown :portage $i
	chmod  g+r $i
end
    
