#!/usr/bin/python3
from sys import argv
from os import environ
import neovim
path=environ['NVIM_LISTEN_ADDRESS']
nvim = neovim.attach('socket',path=path)
nvim.command('tabnew')
nvim.command('term tmux_nvim_new_session \'w3m \\\''+argv[1]+'\\\'\'')
nvim.command('startinsert')
