#!/usr/bin/env python3
from subprocess import Popen,PIPE
from sys import stdout
from sys import argv
a=bytearray([77,211,99,109,253,7,57,91])
stdout.buffer.raw.write(bytearray([0]*25+[255]))
addr=0x18
data=int(argv[1])
print(f"data={data}")

remote_python_code="""
import serial,tty,os
s=serial.Serial(port="/dev/tty-relais-control",baudrate=115200)
tty.setraw(s.fd)
from sys import stdin
s.write(stdin.buffer.read())
print(s.getSettingsDict())
s.flush()
"""

p=Popen(['python','-c',remote_python_code],stdin=PIPE)
for c in a:
    p.stdin.write((c ^ addr ).to_bytes(1,"little"))
for c in a:
    p.stdin.write((c ^ addr ).to_bytes(1,"little"))
for c in a:
    p.stdin.write((c ^ addr ).to_bytes(1,"little"))
p.stdin.write((data).to_bytes(2,"little"))
p.stdin.write((data).to_bytes(2,"little"))
p.stdin.write((data).to_bytes(2,"little"))
p.stdin.flush()
