#!/bin/fish
if test (count argv) -gt 1
  echo read the code bro
end


set f (string trim (find -name '*-'"$ebuild_edit_version"'.ebuild' -exec cat "{}" \;))

set ebuild_path (echo $f|head -n1)

git diff --exit-code -- \'$ebuild_path\'
if not git diff --exit-code -- "$ebuild_path"
    echo
    echo git is not clean. aborting.
    echo
	echo file: $ebuild_path
	echo
    exit 1
end

$s/sed_inplace_insert_between_lines \
' *(python_foreach_impl python_doscript|dobin) +.*' "dobin $argv[1]" '}.*' \
$ebuild_path
