#!/usr/bin/env python3

import http.server                                         
import socketserver                                        
from sys import argv

from argparse import ArgumentParser 

ap=ArgumentParser()
ap.add_argument("-a","--address",nargs="?",default="localhost")
ap.add_argument("-p","--port", type=int,nargs="?",default=8000)
ap.add_argument(dest="directory",type=str,nargs="?",default="")
args=ap.parse_args()

PORT = 8000                                                
                                                           
handler = http.server.SimpleHTTPRequestHandler             
                                                           
with socketserver.TCPServer((args.address,args.port), handler) as httpd: 
    print("Server started at {}:{}".format(args.address,args.port))      
    print('serving dir="{}"'.format(args.directory))
    httpd.serve_forever()                                  
