#!/usr/bin/python3
from sys import argv
from sys import exit
from os import environ
import neovim
path=environ['NVIM_LISTEN_ADDRESS']
nvim = neovim.attach('socket',path=path)

nvim.command( "let "+argv[1]+"="+"'"+argv[2]+"'" )
