#!/usr/bin/python3
from subprocess import check_call,check_output,call
from sys import argv,exit
from os import environ
from os.path import exists,sep as psep

def xrandr_it(filename):
     cmdlines=check_output(['parse_xrandr_conf', filename ]).decode().split("\n")
     for cmdline in cmdlines:
           if len(cmdline.strip()) > 0:
                call(cmdline.split(" "))


if len(argv) > 1 :
    xrandr_conf_file_path = environ["HOME"] + "/.xrandr.conf_"+argv[1]
    modelinefile     = environ['HOME'] + psep +'.modelines_'+argv[1]
else:
    from sys import path
    path.insert(0,'/var/src/pylib')
    from pylib.screen_utils.env import parse_display_var_v2
    display = parse_display_var_v2()
    print(display)
    postfix = ":".join(display.values())
    xrandr_conf_file_path=environ["HOME"] + "/.xrandr.conf_" + postfix
    if not exists( xrandr_conf_file_path ):
        postfix=environ["hostnamE"]
    xrandr_conf_file_path=environ["HOME"] + "/.xrandr.conf_" + postfix
    if not exists( xrandr_conf_file_path ):
        exit(1)
    modelinefile = environ['HOME']+psep+'.modelines_'+postfix

if exists(modelinefile):
    check_call( ['add_modelines', modelinefile] )

xrandr_it( xrandr_conf_file_path )

