#!/usr/bin/env python3

from os import listdir
from time import sleep,time
import os
#print(dir(os))
from sys import exit,stdout
#exit()

while True:
    dirlist=listdir("/run")
    files=[]
    for f in dirlist:
        if f[0:14]=="klima_control_":
            files.append("/run/"+f)
    data={}
    for f in files:
        name=f[19:]
        with open(f) as ff:
            try:
                val = eval(ff.read())
            except SyntaxError:
                val = None
        data.update({name:val})
    maxlen=max([len(i) for i in data.keys()])
    l=maxlen+1
    prefix  = "{:>"+str(l)+"."+str(l)+"} = "
    for k,v in data.items():
        postfix = "{}"
        if not v is None:
            if k[-10:] == "start_time":
                k = k[:-10]+"runtime"
                if type(v) in (float,int):
                    v = time() - v
                if type(v) is float:
                    postfix="{:<.0f}"
        else:
            postfix="{}"
        print((prefix+postfix).format(k,v))
    stdout.buffer.write( 0x1b5b481b5b4a1b5b334a.to_bytes(20,"big") )
    sleep(1)
