#!/usr/bin/env python3
from time import sleep
from subprocess import check_call
from os import environ 
from argparse import ArgumentParser
from math import floor

ap=ArgumentParser()
ap.add_argument("-t","--count_down_time",type=float,default=3)
args=ap.parse_args()

sleep(args.count_down_time%1)
for i in range(floor(args.count_down_time),0,-1):
    print("snapshot in "+str(i)+" [s] ...")
    sleep(1)
print("taking snapshot...",end="")
env=environ.copy()
env.update({"DISPLAY":"skyscraper:0"})
cmd= [ 'xsnap', '-nogui', '-region', '768x1366+0+0', '-file', '/tmp/img.png' ]
check_call(cmd,env=env)
print("done")
show = input("Show snapshot with gpicview (y/n) ?")


if show == "y":
    cmd = [ 'gpicview', '/tmp/img.png' ]
    check_call(cmd)

