#!/mnt/home/username/gentoo/bin/bash
# Copyright 2006-2014 Gentoo Foundation; Distributed under the GPL v2
# $Id: startprefix.in 61219 2012-09-04 19:05:55Z grobian $

# Fabian Groffen <grobian@gentoo.org> -- 2007-03-10
# Enters the prefix environment by starting a login shell from the
# prefix.  The SHELL environment variable is elevated in order to make
# applications that start login shells to work, such as `screen`.

# if you come from a substantially polluted environment (another
# Prefix), a cleanup as follows resolves most oddities I've ever seen:
# env -i HOME=$HOME TERM=$TERM USER=$USER $SHELL -l
# hence this script starts the Prefix shell like this


if [[ ${SHELL#${EPREFIX}} != ${SHELL} ]] ; then
	echo "You appear to be in prefix already (SHELL=$SHELL)" > /dev/stderr
	exit -1
fi

# not all systems have the same location for shells, however what it
# boils down to, is that we need to know what the shell is, and then we
# can find it in the bin dir of our prefix
SHELL='bash'
# set the prefix shell in the environment
export SHELL=${EPREFIX}/bin/${SHELL}
# check if the shell exists
if [[ ! -x $SHELL ]] ; then
    echo no shell at path: $SHELL
	echo "Failed to find the Prefix shell, this is probably" > /dev/stderr
	echo "because you didn't emerge the shell ${SHELL##*/}" > /dev/stderr
	exit -1
fi

# give a small notice
echo "Entering Gentoo Prefix ${EPREFIX}"
# start the login shell, clean the entire environment but what's needed
USER=$(echo $USER|tr -d " ")

###################
### retain vars ###
###################
RETAIN="HOME=$HOME TERM=$TERM USER=$USER SHELL=$SHELL PHOME=$PHOME NHOME=$NHOME"
RETAIN="${RETAIN} EROOT=$EROOT"
RETAIN="${RETAIN} LANG=$LANG LC_COLLATE=$LC_COLLATE LC_CTYPE=$LC_CTYPE LANGUAGE=$LANGUAGE"
##################
# PROFILEREAD is necessary on SUSE not to wipe the env on shell start
[[ -n ${PROFILEREAD} ]] && RETAIN+=" PROFILEREAD=$PROFILEREAD"
# ssh-agent is handy to keep, of if set, inherit it
[[ -n ${SSH_AUTH_SOCK} ]] && RETAIN+=" SSH_AUTH_SOCK=$SSH_AUTH_SOCK"
# if we're on some X terminal, makes sense to inherit that too
[[ -n ${DISPLAY} ]] && RETAIN+=" DISPLAY=$DISPLAY"
# do it!
echo Retain vars: $RETAIN
# -l  : behave as login shell
if [[ ${new_nvim} -eq 1 ]]&& [[ ${tmux_i} -eq 1 ]] ;then
    echo i
    env -i $RETAIN $SHELL -l -c 'fish -c "tmux -S /tmp/tmux-10054/ti new-session -s '${tmux_session_name}' n"'

elif [[ ${new_nvim} -eq 1 ]]&& [[ ${tmux_ii} -eq 1 ]] ;then
    echo ii
    env -i $RETAIN $SHELL -l -c 'fish -c "tmux -S /tmp/tmux-10054/tii new-session -s '${tmux_session_name}' n"'

elif [[ ${tmux_i} -eq 1 ]];then
    echo i new_nvim
    env -i $RETAIN $SHELL -l -c 'fish -c "tmux -S /tmp/tmux-10054/ti new-session -A -s '${tmux_session_name}'"'

elif [[ ${tmux_ii} -eq 1 ]];then
    echo ii new nvim
    env -i $RETAIN $SHELL -l -c 'fish -c "tmux -S /tmp/tmux-10054/tii new-session -A -s '${tmux_session_name}'"'

else
    env -i $RETAIN $SHELL -l
fi

# and leave a message when we exit... the shell might return non-zero
# without having real problems, so don't send alarming messages about
# that
echo "Leaving Gentoo Prefix with exit status $?"
