#!/bin/bash
export DISPLAY=":0"
export WAYLAND_USER="wayland"
export WAYVNC_USER="wayvnc"
export WLR_RENDERER="gles2"
export WLR_LIBINPUT_NO_DEVICES="0"
export WLR_BACKENDS="headless,libinput"
export WAYLAND_DISPLAY="wayland-0"
export XDG_RUNTIME_DIR="/run/wayland"

qtile_config_file="${HOME}/.config/qtile/config.py"
compositor_cmd="qtile start -b wayland -l WARNING -c ${qtile_config_file}"

sudo rc-service seatd start

if ! [[ -e "${XDG_RUNTIME_DIR}" ]];then
    echo sudo mkdir "${XDG_RUNTIME_DIR}"
    echo sudo chown "${USER}:${WAYLAND_USER}" "${XDG_RUNTIME_DIR}
    echo sudo chmod g+rwxs  "${XDG_RUNTIME_DIR}
fi

echo starting compositor, some of env:
env | grep -iE 'way|displ|wlr|xdg'
eval "${compositor_cmd} &"

sleep 0.5
echo setting xhost perms ...
while ! xhost "+local:" ; do
    echo setting xhost perms ... 
    jobs
    sleep 1
done

#echo setting perms1 ...
#while ! chmod g+rw \
#                 "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" \
#                 "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}".lock;do
#    echo setting perms1 ...
#    sleep 1
#done

port_offset=0
for i in 1 2 3 ;do
    echo starting wayvnc "${i}"
    cmdline="wayvnc -o HEADLESS-${i} -S ${XDG_RUNTIME_DIR}/wayvncctl-$((${i} + ${port_offset} )) -Ldebug --max-fps=60 --gpu 192.168.177.2 590$(( ${i} + ${port_offset} ))"
    while true;do
        echo doing loop
        eval "${cmdline} &"
        pid=$(jobs -rp|tail -n1)
        pid_dir="/proc/${pid}"
        sleep 5
        if [[ -d ${pid_dir} ]];then
            if [[ $(cat "${pid_dir}"/cmdline | tr \\00 \\40) = "$cmdline " ]] ;then
                #reset
                echo break
                break
            fi
        fi
        sleep 1
        echo no wayvnc found
    done
done

echo wlr setup ...
wlr-randr --output HEADLESS-1 --pos 0,336 --on --output HEADLESS-2 --custom-mode 1033x581 --pos 1366,581 --on --output HEADLESS-3 --on --pos 1366,0 --custom-mode 1033x581

# the more local the key repeat the better
xset r off

echo starting st
while ! xhost +local: ;do
    echo waiting...
    sleep 1
done
st
wait
