#!/usr/bin/env python3
from sys import argv
from re import match

if not match("",argv[1]):
    raise Exception("Error wrong argument supplied. Expecting pid.")

keys="size resident shared trs lrs drs dt".split(" ")

with open("/proc/"+str(argv[1])+"/statm") as f:
	values=f.read().strip().split(" ")

for k,v  in zip(keys,values):
    v=int(v)*4
    if v <=9999:
        print("{:>10.10s} = {} Kb".format(k,v))
    else:
        v/=1024
        s="{:>10.10s} = {:.1f} Mb".format(k,v)
        if v%1!=0:
            s="{:30} {:>10}".format(s,"(rnd)")
        else:
            s="{:30} {:>10}".format(s,"")
        print(s)
