#!/bin/fish
mkdir -p /tmp/tmux-(id -u)
if test (count $argv) -eq 1
        tmux -S /tmp/tmux-(id -u)/(hostname) new-session $argv[1]
else if test (count $argv) -eq 2
        tmux -S /tmp/tmux-(id -u)/(hostname) new-session $argv[1] -c argv[2]
else
        tmux -S /tmp/tmux-(id -u)/(hostname) new-session
end
