#!/bin/fish
mkdir -p /tmp/tmux-(id -u) 
set tmuxcmd "tmux -S /tmp/tmux-"(id -u)"/"(hostname)

set sessionname $argv[1]

if eval $tmuxcmd  has-session -t $sessionname
        eval $tmuxcmd attach-session -t $sessionname
elseif set -q TMUX
        eval $tmuxcmd switch-client -t $sessionname
elseif not test $argv[2] -eq ""
        eval $tmuxcmd new-session -s $sessionname -c $argv[2]
else
        eval $tmuxcmd new-session -s $sessionname
end
