#!/bin/sh

socket_name="$(hostname)"

if [[ -v DISPLAY ]] && [[ -n "${DISPLAY}" ]] ; then
    p0="$(echo ${DISPLAY}|cut -d":" -f1)"
    p1="$(echo ${DISPLAY}|cut -d":" -f2)"
    [[ -z $p0 ]] && p0="${host}"
    display="${p0}_${p1}"
    display="$(echo "${display}" | sed -E 's/[^a-zA-Z0-9]/_/g')"
fi

echo $display

xpos="$(xdotool getactivewindow getwindowgeometry | grep Position: |cut -d: -f2 | sed -r 's/\s*(\w*)\s*/\1/'| cut -d, -f1)"
if [[ -n $xpos ]];then
    xpos=$(( ${xpos}  -  ( ${xpos} % 10 ) ))
else
    xpos="none"
fi
session_name="${display}_${xpos}"

echo socket name: $socket_name

if [[ -e "/tmp/tmux-$(id -u)" ]];then
    echo tmux attach...
    echo $session_name
    tmux -L "${socket_name}" new-session -A -s "${session_name}"
else
    echo new tmux session
    echo $session_name
    tmux -L "${socket_name}" new-session -s "${session_name}"
fi
    
