#!/bin/fish
set cmd "wget"
set cmd $cmd "--recursive"
#set cmd $cmd "--span-hosts"
set cmd $cmd "--level=$argv[1]"
set cmd $cmd "--no-directories"
set cmd $cmd "--adjust-extension"
set cmd $cmd "--convert-links"
set cmd $cmd "--page-requisites"
set cmd $cmd "--no-parent"
set cmd $cmd "--execute robots=off"
set cmd $cmd "--no-verbose"
set cmd $cmd $argv[2]

echo $cmd
read
eval $cmd

