#!/bin/sh
if [[ "${1}" -eq  0 ]];then
	xclip -selection primary -o > "${CLIPBOARD_FILE}"
elif [[ "${1}" -eq  1 ]];then
	xclip -selection clipboard -o > "${CLIPBOARD_FILE}"
fi && echo -n 'b' > "${CLIPBOARD_META_FILE}"

