#!/usr/bin/python3

__doc__="""
This script initializes the 2nd X-server.
"""

from subprocess import call,check_call,DEVNULL
from time import sleep
from os import environ

def main():
    xhost_env=environ.copy()
    xhost_env['DISPLAY']='skyscraper:0'
    if not 0 == call(['xhost'],env=xhost_env,stderr=DEVNULL,stdout=DEVNULL):
        check_call(['ssh','root@skyscraper','rind','rc-service','xserver','restart'])
    sleep(1.5)
    check_call([environ['HOME']+'/.xinitrc_skyscraper'])

if __name__ == "__main__":
    main()
    
# vim: set nowrap foldlevel=0 foldnestmax=0 foldmethod=indent :
