#!/usr/bin/python3
from subprocess import call
from os import environ

#from psutil import process_iter
#from re import match


#def is_i3_running():
#    found=False
#    for p in process_iter():
#        for i in  p.cmdline():
#            if match(".*i3$",i):
#                found=True
#    return found 
#

# remove NVIM_LISTEN_ADDRESS because xservers cannot be nested inside nvim
env=environ.copy()
env.pop("NVIM_LISTEN_ADDRESS")

call( [ 'xinit', environ['HOME']+'/.xinitrc_skyscraper', '--', environ['HOME']+'/.xserverrc_skyscraper' ],env=env)

# vim: set foldlevel=0 foldnestmax=2 foldmethod=indent :
